"""Clustering PynamoDB models for article clustering and embeddings."""

from pynamodb.models import Model
from pynamodb.attributes import (
    UnicodeAttribute,
    NumberAttribute,
    ListAttribute,
    BooleanAttribute,
    MapAttribute,
)
from pynamodb.indexes import GlobalSecondaryIndex, AllProjection

from app.config import settings


class ArticleIdIndex(GlobalSecondaryIndex):
    """Index for looking up cluster assignments by article_id."""

    class Meta:
        index_name = "article-id-index"
        projection = AllProjection()
        read_capacity_units = 5
        write_capacity_units = 5

    article_id = UnicodeAttribute(hash_key=True)


class ArticleClusterModel(Model):
    """
    Stores cluster assignments for each article.

    Partition Key: cluster_id (String)
    Sort Key: article_id (String)
    TTL: 7 days (automatic cleanup)

    Attributes:
    - cluster_id: ID of the cluster this article belongs to
    - article_id: ID of the article
    - assigned_at: Unix timestamp when article was assigned to cluster
    - confidence_score: 0-1 score representing distance from cluster centroid
    - ttl: Unix timestamp for automatic expiration (7 days from creation)
    """

    class Meta:
        table_name = f"{settings.dynamodb_table_prefix}article_clusters"
        region = settings.aws_region
        host = settings.dynamodb_endpoint_url
        read_capacity_units = 5
        write_capacity_units = 5

    # Keys
    cluster_id = UnicodeAttribute(hash_key=True)
    article_id = UnicodeAttribute(range_key=True)

    # Indexes
    article_id_index = ArticleIdIndex()

    # Attributes
    assigned_at = NumberAttribute()
    confidence_score = NumberAttribute()  # 0-1, distance from centroid
    ttl = NumberAttribute()  # Unix timestamp for automatic cleanup


class TopArticleItem(MapAttribute):
    """Structure for top articles in cluster metadata."""

    article_id = UnicodeAttribute()
    title = UnicodeAttribute()
    engagement_score = NumberAttribute()


class ClusterMetadataModel(Model):
    """
    Stores metadata and labels for clusters.

    Partition Key: cluster_id (String)
    No Sort Key
    TTL: 7 days (automatic cleanup)

    Attributes:
    - cluster_id: Unique cluster identifier
    - label: Human-readable cluster label (auto-generated by Claude)
    - keywords: Top 5 keywords extracted via TF-IDF
    - description: Cluster description (auto-generated by Claude)
    - article_count: Number of articles in this cluster
    - size_category: SMALL (5-10), MEDIUM (11-50), LARGE (51+)
    - diversity_score: 0-1 score of average pairwise cosine distance
    - centroid_embedding: 1536-dimensional average embedding vector
    - top_articles: Up to 10 highest engagement articles with confidence
    - created_at: Unix timestamp when cluster was created
    - updated_at: Unix timestamp of last update
    - ttl: Unix timestamp for automatic cleanup
    """

    class Meta:
        table_name = f"{settings.dynamodb_table_prefix}cluster_metadata"
        region = settings.aws_region
        host = settings.dynamodb_endpoint_url
        read_capacity_units = 5
        write_capacity_units = 5

    # Keys
    cluster_id = UnicodeAttribute(hash_key=True)

    # Attributes
    label = UnicodeAttribute()
    keywords = ListAttribute(of=UnicodeAttribute)
    description = UnicodeAttribute()
    article_count = NumberAttribute()
    size_category = UnicodeAttribute()  # SMALL, MEDIUM, LARGE
    diversity_score = NumberAttribute()  # 0-1
    centroid_embedding = ListAttribute(of=NumberAttribute)  # 1536 dimensions
    top_articles = ListAttribute(of=TopArticleItem)  # Up to 10 articles
    created_at = NumberAttribute()
    updated_at = NumberAttribute()
    ttl = NumberAttribute()  # Unix timestamp for automatic cleanup


class ArticleEmbeddingModel(Model):
    """
    Stores cached embeddings for articles to avoid redundant API calls.

    Partition Key: article_id (String)
    No Sort Key
    TTL: 7 days (automatic cleanup)

    Attributes:
    - article_id: ID of the article
    - embedding: 1536-dimensional embedding vector (from OpenAI text-embedding-3-small)
    - embedding_model: Model identifier ("text-embedding-3-small")
    - generated_at: Unix timestamp when embedding was generated
    - ttl: Unix timestamp for automatic cleanup
    """

    class Meta:
        table_name = f"{settings.dynamodb_table_prefix}article_embeddings"
        region = settings.aws_region
        host = settings.dynamodb_endpoint_url
        read_capacity_units = 5
        write_capacity_units = 5

    # Keys
    article_id = UnicodeAttribute(hash_key=True)

    # Attributes
    embedding = ListAttribute(of=NumberAttribute)  # 1536 dimensions
    embedding_model = UnicodeAttribute()  # "text-embedding-3-small"
    generated_at = NumberAttribute()
    ttl = NumberAttribute()  # Unix timestamp for automatic cleanup
